In [60]:
import torch

Temperature Model

In [61]:
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [62]:
#define model 
def model(t_u, w1, w2, b):
    return w2*t_u**2+w1*t_u+b

In [63]:
#define loss function
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [64]:
w1 = torch.ones(())
w2 = torch.ones(())
b = torch.zeros(())
t_p = model(t_u, w1, w2, b)
t_p


tensor([1310.1901, 3180.7100, 3445.4399, 6789.5103, 3225.9900, 2440.1101,
        1183.1101,  497.0399, 2390.9600, 3708.5601, 4746.9600])

In [65]:
#check value of loss
loss = loss_fn(t_p, t_c)
loss


tensor(11709471.)

In [68]:
delta = 0.1
loss_rate_of_change_w1 = \
(loss_fn(model(t_u, w1 + delta,w2, b), t_c) - loss_fn(model(t_u, w1 - delta,w2, b), t_c)) / (2.0 * delta)

In [69]:
print(loss_rate_of_change_w1)

tensor(361810.)


In [70]:
learning_rate = 1e-2
w1 = w1 - learning_rate * loss_rate_of_change_w1

In [71]:
#same with w2

loss_rate_of_change_w2 = \
(loss_fn(model(t_u, w1,w2 + delta, b), t_c) - loss_fn(model(t_u, w1, w2+delta, b), t_c)) / (2.0 * delta)
w2 = w2 - learning_rate * loss_rate_of_change_w2


In [72]:
#same with b

In [73]:
loss_rate_of_change_b = \
    (loss_fn(model(t_u, w1, w2, b + delta), t_c) -
     loss_fn(model(t_u, w1, w2, b - delta), t_c)) / (2.0 * delta)
b = b - learning_rate * loss_rate_of_change_b


In [74]:
#Defining the gradient function
def dloss_fn(t_p, t_c):
    dsq_diffs = 2 * (t_p - t_c) / t_p.size(0)
    return dsq_diffs

def dmodel_dw1(t_u, w1, w2, b):
  return t_u

def dmodel_dw2(t_u, w1, w2, b):
  return t_u*2*w2


def dmodel_db(t_u, w1, w2, b):
  return 1.0


def grad_fn(t_u, t_c, t_p, w1, w2, b):
  dloss_dtp = dloss_fn(t_p, t_c)
  dloss_dw1 = dloss_dtp * dmodel_dw1(t_u, w1, w2, b)
  dloss_dw2 = dloss_dtp * dmodel_dw2(t_u, w1, w2, b)
  dloss_db = dloss_dtp * dmodel_db(t_u, w1, w2, b)
  return torch.stack([dloss_dw1.sum(), dloss_dw2.sum(), dloss_db.sum()])

In [75]:
#define training loop
def training_loop(n_epochs, learning_rate, params, t_u, t_c):
  for epoch in range(1, n_epochs + 1):
    w1, w2, b = params
    t_p = model(t_u, w1, w2, b)
    loss = loss_fn(t_p, t_c)
    grad = grad_fn(t_u, t_c, t_p, w1, w2, b)
    params = params - learning_rate * grad
    print('Epoch %d, Loss %f' % (epoch, float(loss)))
  return params


In [77]:
#Execute training loop
training_loop(
    n_epochs = 100,
    learning_rate = 1e-2,
    params = torch.tensor([1.0, 1.0, 0.0]),
    t_u = t_u,
    t_c = t_c)

Epoch 1, Loss 11709471.000000
Epoch 2, Loss 608308431945728.000000
Epoch 3, Loss 1627411056994160601881343164416.000000
Epoch 4, Loss inf
Epoch 5, Loss inf
Epoch 6, Loss nan
Epoch 7, Loss nan
Epoch 8, Loss nan
Epoch 9, Loss nan
Epoch 10, Loss nan
Epoch 11, Loss nan
Epoch 12, Loss nan
Epoch 13, Loss nan
Epoch 14, Loss nan
Epoch 15, Loss nan
Epoch 16, Loss nan
Epoch 17, Loss nan
Epoch 18, Loss nan
Epoch 19, Loss nan
Epoch 20, Loss nan
Epoch 21, Loss nan
Epoch 22, Loss nan
Epoch 23, Loss nan
Epoch 24, Loss nan
Epoch 25, Loss nan
Epoch 26, Loss nan
Epoch 27, Loss nan
Epoch 28, Loss nan
Epoch 29, Loss nan
Epoch 30, Loss nan
Epoch 31, Loss nan
Epoch 32, Loss nan
Epoch 33, Loss nan
Epoch 34, Loss nan
Epoch 35, Loss nan
Epoch 36, Loss nan
Epoch 37, Loss nan
Epoch 38, Loss nan
Epoch 39, Loss nan
Epoch 40, Loss nan
Epoch 41, Loss nan
Epoch 42, Loss nan
Epoch 43, Loss nan
Epoch 44, Loss nan
Epoch 45, Loss nan
Epoch 46, Loss nan
Epoch 47, Loss nan
Epoch 48, Loss nan
Epoch 49, Loss nan
Epoch 50, Lo

tensor([nan, nan, nan])

Our training loss blew up!!


In [78]:
training_loop(
    n_epochs = 100,
    learning_rate = 1e-4,
    params = torch.tensor([1.0, 1.0,  0.0]),
    t_u = t_u,
    t_c = t_c)


Epoch 1, Loss 11709471.000000
Epoch 2, Loss 59171246080.000000
Epoch 3, Loss 1540233271583965184.000000
Epoch 4, Loss 1059024588712591941253847222059008.000000
Epoch 5, Loss inf
Epoch 6, Loss inf
Epoch 7, Loss nan
Epoch 8, Loss nan
Epoch 9, Loss nan
Epoch 10, Loss nan
Epoch 11, Loss nan
Epoch 12, Loss nan
Epoch 13, Loss nan
Epoch 14, Loss nan
Epoch 15, Loss nan
Epoch 16, Loss nan
Epoch 17, Loss nan
Epoch 18, Loss nan
Epoch 19, Loss nan
Epoch 20, Loss nan
Epoch 21, Loss nan
Epoch 22, Loss nan
Epoch 23, Loss nan
Epoch 24, Loss nan
Epoch 25, Loss nan
Epoch 26, Loss nan
Epoch 27, Loss nan
Epoch 28, Loss nan
Epoch 29, Loss nan
Epoch 30, Loss nan
Epoch 31, Loss nan
Epoch 32, Loss nan
Epoch 33, Loss nan
Epoch 34, Loss nan
Epoch 35, Loss nan
Epoch 36, Loss nan
Epoch 37, Loss nan
Epoch 38, Loss nan
Epoch 39, Loss nan
Epoch 40, Loss nan
Epoch 41, Loss nan
Epoch 42, Loss nan
Epoch 43, Loss nan
Epoch 44, Loss nan
Epoch 45, Loss nan
Epoch 46, Loss nan
Epoch 47, Loss nan
Epoch 48, Loss nan
Epoch 49,

tensor([nan, nan, nan])

Our traing doesn't blow up, but it converges very slowly.... let's normalize the inputs: 

In [79]:
t_un = 0.1 * t_u

In [80]:
training_loop(
    n_epochs = 100,
    learning_rate = 1e-2,
    params = torch.tensor([1.0, 1.0, 0.0]),
    t_u = t_un,
    t_c = t_c)

Epoch 1, Loss 675.794373
Epoch 2, Loss 31929.195312
Epoch 3, Loss 35335692.000000
Epoch 4, Loss 57148931309568.000000
Epoch 5, Loss 145894348871649047689035776.000000
Epoch 6, Loss inf
Epoch 7, Loss inf
Epoch 8, Loss nan
Epoch 9, Loss nan
Epoch 10, Loss nan
Epoch 11, Loss nan
Epoch 12, Loss nan
Epoch 13, Loss nan
Epoch 14, Loss nan
Epoch 15, Loss nan
Epoch 16, Loss nan
Epoch 17, Loss nan
Epoch 18, Loss nan
Epoch 19, Loss nan
Epoch 20, Loss nan
Epoch 21, Loss nan
Epoch 22, Loss nan
Epoch 23, Loss nan
Epoch 24, Loss nan
Epoch 25, Loss nan
Epoch 26, Loss nan
Epoch 27, Loss nan
Epoch 28, Loss nan
Epoch 29, Loss nan
Epoch 30, Loss nan
Epoch 31, Loss nan
Epoch 32, Loss nan
Epoch 33, Loss nan
Epoch 34, Loss nan
Epoch 35, Loss nan
Epoch 36, Loss nan
Epoch 37, Loss nan
Epoch 38, Loss nan
Epoch 39, Loss nan
Epoch 40, Loss nan
Epoch 41, Loss nan
Epoch 42, Loss nan
Epoch 43, Loss nan
Epoch 44, Loss nan
Epoch 45, Loss nan
Epoch 46, Loss nan
Epoch 47, Loss nan
Epoch 48, Loss nan
Epoch 49, Loss nan
E

tensor([nan, nan, nan])

In [81]:
#increase epochs
training_loop(
    n_epochs = 5000,
    learning_rate = 1e-2,
    params = torch.tensor([1.0, 1.0, 0.0]),
    t_u = t_un,
    t_c = t_c)

Epoch 1, Loss 675.794373
Epoch 2, Loss 31929.195312
Epoch 3, Loss 35335692.000000
Epoch 4, Loss 57148931309568.000000
Epoch 5, Loss 145894348871649047689035776.000000
Epoch 6, Loss inf
Epoch 7, Loss inf
Epoch 8, Loss nan
Epoch 9, Loss nan
Epoch 10, Loss nan
Epoch 11, Loss nan
Epoch 12, Loss nan
Epoch 13, Loss nan
Epoch 14, Loss nan
Epoch 15, Loss nan
Epoch 16, Loss nan
Epoch 17, Loss nan
Epoch 18, Loss nan
Epoch 19, Loss nan
Epoch 20, Loss nan
Epoch 21, Loss nan
Epoch 22, Loss nan
Epoch 23, Loss nan
Epoch 24, Loss nan
Epoch 25, Loss nan
Epoch 26, Loss nan
Epoch 27, Loss nan
Epoch 28, Loss nan
Epoch 29, Loss nan
Epoch 30, Loss nan
Epoch 31, Loss nan
Epoch 32, Loss nan
Epoch 33, Loss nan
Epoch 34, Loss nan
Epoch 35, Loss nan
Epoch 36, Loss nan
Epoch 37, Loss nan
Epoch 38, Loss nan
Epoch 39, Loss nan
Epoch 40, Loss nan
Epoch 41, Loss nan
Epoch 42, Loss nan
Epoch 43, Loss nan
Epoch 44, Loss nan
Epoch 45, Loss nan
Epoch 46, Loss nan
Epoch 47, Loss nan
Epoch 48, Loss nan
Epoch 49, Loss nan
E

tensor([nan, nan, nan])

Rewrite using autograd 

In [82]:

def model(t_u, w1, w2, b):
   return w2*t_u**2+w1*t_u+b


def loss_fn(t_p, t_c):
   squared_diffs = (t_p - t_c)**2
   return squared_diffs.mean()

params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)



In [83]:
loss = loss_fn(model(t_u, *params), t_c)
loss.backward()

In [84]:
params.grad

tensor([3.6181e+05, 2.3149e+07, 5.9642e+03])

At this point, the grad attribute of params contains the derivatives of the loss with respect to each element of params.

In [95]:
#Full autograd enabled 
def training_loop(n_epochs, learning_rate, params, t_u, t_c):
  for epoch in range(1, n_epochs + 1):
      if params.grad is not None:
          params.grad.zero_()

      t_p = model(t_u, *params)
      loss = loss_fn(t_p, t_c)
      loss.backward()

      with torch.no_grad():
       params -= learning_rate * params.grad

      if epoch % 500 == 0:
                    print('Epoch %d, Loss %f' % (epoch, float(loss)))

  return params



In [99]:
training_loop(
  n_epochs = 5000,
  learning_rate = 1e-2,
  params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True),
  t_u = t_un,
  t_c = t_c)

Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan


tensor([nan, nan, nan], requires_grad=True)

In [87]:
#using Pytorch optimizers 
import torch.optim as optim
dir(optim)

['ASGD',
 'Adadelta',
 'Adagrad',
 'Adam',
 'AdamW',
 'Adamax',
 'LBFGS',
 'NAdam',
 'Optimizer',
 'RAdam',
 'RMSprop',
 'Rprop',
 'SGD',
 'SparseAdam',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_functional',
 '_multi_tensor',
 'lr_scheduler',
 'swa_utils']

In [88]:
#constructing the optimizer
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-5
optimizer = optim.SGD([params], lr=learning_rate)

In [89]:
#trying out the optimizer
t_p = model(t_u, *params)
loss = loss_fn(t_p, t_c)

optimizer.zero_grad()
loss.backward()
optimizer.step()

params


tensor([-2.6181e+00, -2.3049e+02, -5.9642e-02], requires_grad=True)

In [103]:
#update the training loop
def training_loop(n_epochs, optimizer, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        t_p = model(t_u, *params)
        loss = loss_fn(t_p, t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
    return params

In [104]:
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)


In [105]:
training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    t_u = t_un,
    t_c = t_c)

Epoch 500, Loss nan
Epoch 1000, Loss nan
Epoch 1500, Loss nan
Epoch 2000, Loss nan
Epoch 2500, Loss nan
Epoch 3000, Loss nan
Epoch 3500, Loss nan
Epoch 4000, Loss nan
Epoch 4500, Loss nan
Epoch 5000, Loss nan


tensor([nan, nan, nan], requires_grad=True)

In [106]:
#using Adam instead of SGD
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-1
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 2000,
    optimizer = optimizer,
    params = params,
    t_u = t_u,
    t_c = t_c)

Epoch 500, Loss 4.844499
Epoch 1000, Loss 3.785645
Epoch 1500, Loss 3.466678
Epoch 2000, Loss 3.406404


tensor([-0.1081,  0.0060, -1.4510], requires_grad=True)

In [107]:
n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)
shuffled_indices = torch.randperm(n_samples)
train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]
train_indices, val_indices

(tensor([3, 5, 8, 2, 4, 7, 0, 9, 6]), tensor([ 1, 10]))

In [108]:
train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]
val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]
train_t_un = 0.1 * train_t_u
val_t_un = 0.1 * val_t_u


In [109]:
def training_loop(n_epochs, optimizer, params, train_t_u, val_t_u,
              train_t_c, val_t_c):
  for epoch in range(1, n_epochs + 1):
      train_t_p = model(train_t_u, *params)
      train_loss = loss_fn(train_t_p, train_t_c)
      val_t_p = model(val_t_u, *params)
      val_loss = loss_fn(val_t_p, val_t_c)

      optimizer.zero_grad()
      train_loss.backward()
      optimizer.step()

      if epoch <= 3 or epoch % 500 == 0:
              print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                    f" Validation loss {val_loss.item():.4f}")
  return params



In [119]:
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-5
optimizer = optim.SGD([params], lr=learning_rate)


training_loop(
    n_epochs = 3000,
    optimizer = optimizer,
    params = params,
    train_t_u = train_t_un,
    val_t_u = val_t_un,
    train_t_c = train_t_c,
    val_t_c = val_t_c)

Epoch 1, Training loss 649.7477, Validation loss 793.0045
Epoch 2, Training loss 622.8081, Validation loss 756.0198
Epoch 3, Training loss 597.0123, Validation loss 720.6838
Epoch 500, Training loss 14.7558, Validation loss 8.2058
Epoch 1000, Training loss 14.2907, Validation loss 8.1723
Epoch 1500, Training loss 13.8438, Validation loss 8.1377
Epoch 2000, Training loss 13.4143, Validation loss 8.1055
Epoch 2500, Training loss 13.0017, Validation loss 8.0755
Epoch 3000, Training loss 12.6052, Validation loss 8.0477


tensor([ 0.6267,  0.2832, -0.1309], requires_grad=True)